style = "blue"

margin = 80
indent = 2

align_assignment = true
align_struct_field = true
always_for_in = true
always_use_return = true
annotate_untyped_fields_with_any = false
conditional_to_if = true
format_docstrings = true
import_to_using = true
remove_extra_newlines = true
separate_kwargs_with_semicolon = true
trailing_comma = true
trailing_zero = true
whitespace_in_kwargs = false
whitespace_typedefs = true
whitespace_ops_in_indices = true

ignore = ["assets", "docs"]